<?xml version="1.0" encoding="utf-8"?><Database Name="QLNongSan" Class="dbQLNongSanDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LAPTOP-LMCRTTA9\LOCAL;Initial Catalog=QLNongSan;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="QLNongSanConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.LoaiSanPham" Member="LoaiSanPhams">
    <Type Name="LoaiSanPham">
      <Column Name="Ma_LSP" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ten_LSP" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="LoaiSanPham_SanPham" Member="SanPhams" ThisKey="Ma_LSP" OtherKey="Ma_LSP" Type="SanPham" />
    </Type>
  </Table>
  <Table Name="dbo.SanPham" Member="SanPhams">
    <Type Name="SanPham">
      <Column Name="Ma_SP" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ma_LSP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ten_SP" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Giaban" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Khuyenmai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Giakhuyenmai" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Mota" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Hinhanh" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Ngaydangban" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Soluongton" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Donvitinh" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="LoaiSanPham_SanPham" Member="LoaiSanPham" ThisKey="Ma_LSP" OtherKey="Ma_LSP" Type="LoaiSanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="Ma_KH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Hoten_KH" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Taikhoan_KH" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Matkhau_KH" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Gmail_KH" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Xacthucgmail" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Anhdaidien_KH" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Diachi_KH" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Dienthoai_KH" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
    </Type>
  </Table>
</Database>