#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_CoSo.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLNongSan")]
	public partial class dbQLNongSanDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertLoaiSanPham(LoaiSanPham instance);
    partial void UpdateLoaiSanPham(LoaiSanPham instance);
    partial void DeleteLoaiSanPham(LoaiSanPham instance);
    partial void InsertSanPham(SanPham instance);
    partial void UpdateSanPham(SanPham instance);
    partial void DeleteSanPham(SanPham instance);
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    #endregion
		
		public dbQLNongSanDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QLNongSanConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLNongSanDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLNongSanDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLNongSanDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLNongSanDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<LoaiSanPham> LoaiSanPhams
		{
			get
			{
				return this.GetTable<LoaiSanPham>();
			}
		}
		
		public System.Data.Linq.Table<SanPham> SanPhams
		{
			get
			{
				return this.GetTable<SanPham>();
			}
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiSanPham")]
	public partial class LoaiSanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Ma_LSP;
		
		private string _Ten_LSP;
		
		private EntitySet<SanPham> _SanPhams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_LSPChanging(int value);
    partial void OnMa_LSPChanged();
    partial void OnTen_LSPChanging(string value);
    partial void OnTen_LSPChanged();
    #endregion
		
		public LoaiSanPham()
		{
			this._SanPhams = new EntitySet<SanPham>(new Action<SanPham>(this.attach_SanPhams), new Action<SanPham>(this.detach_SanPhams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_LSP", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Ma_LSP
		{
			get
			{
				return this._Ma_LSP;
			}
			set
			{
				if ((this._Ma_LSP != value))
				{
					this.OnMa_LSPChanging(value);
					this.SendPropertyChanging();
					this._Ma_LSP = value;
					this.SendPropertyChanged("Ma_LSP");
					this.OnMa_LSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_LSP", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Ten_LSP
		{
			get
			{
				return this._Ten_LSP;
			}
			set
			{
				if ((this._Ten_LSP != value))
				{
					this.OnTen_LSPChanging(value);
					this.SendPropertyChanging();
					this._Ten_LSP = value;
					this.SendPropertyChanged("Ten_LSP");
					this.OnTen_LSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiSanPham_SanPham", Storage="_SanPhams", ThisKey="Ma_LSP", OtherKey="Ma_LSP")]
		public EntitySet<SanPham> SanPhams
		{
			get
			{
				return this._SanPhams;
			}
			set
			{
				this._SanPhams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SanPhams(SanPham entity)
		{
			this.SendPropertyChanging();
			entity.LoaiSanPham = this;
		}
		
		private void detach_SanPhams(SanPham entity)
		{
			this.SendPropertyChanging();
			entity.LoaiSanPham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SanPham")]
	public partial class SanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Ma_SP;
		
		private int _Ma_LSP;
		
		private string _Ten_SP;
		
		private System.Nullable<decimal> _Giaban;
		
		private System.Nullable<int> _Khuyenmai;
		
		private System.Nullable<decimal> _Giakhuyenmai;
		
		private string _Mota;
		
		private string _Hinhanh;
		
		private System.Nullable<System.DateTime> _Ngaydangban;
		
		private System.Nullable<int> _Soluongton;
		
		private string _Donvitinh;
		
		private EntityRef<LoaiSanPham> _LoaiSanPham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_SPChanging(int value);
    partial void OnMa_SPChanged();
    partial void OnMa_LSPChanging(int value);
    partial void OnMa_LSPChanged();
    partial void OnTen_SPChanging(string value);
    partial void OnTen_SPChanged();
    partial void OnGiabanChanging(System.Nullable<decimal> value);
    partial void OnGiabanChanged();
    partial void OnKhuyenmaiChanging(System.Nullable<int> value);
    partial void OnKhuyenmaiChanged();
    partial void OnGiakhuyenmaiChanging(System.Nullable<decimal> value);
    partial void OnGiakhuyenmaiChanged();
    partial void OnMotaChanging(string value);
    partial void OnMotaChanged();
    partial void OnHinhanhChanging(string value);
    partial void OnHinhanhChanged();
    partial void OnNgaydangbanChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaydangbanChanged();
    partial void OnSoluongtonChanging(System.Nullable<int> value);
    partial void OnSoluongtonChanged();
    partial void OnDonvitinhChanging(string value);
    partial void OnDonvitinhChanged();
    #endregion
		
		public SanPham()
		{
			this._LoaiSanPham = default(EntityRef<LoaiSanPham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_SP", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Ma_SP
		{
			get
			{
				return this._Ma_SP;
			}
			set
			{
				if ((this._Ma_SP != value))
				{
					this.OnMa_SPChanging(value);
					this.SendPropertyChanging();
					this._Ma_SP = value;
					this.SendPropertyChanged("Ma_SP");
					this.OnMa_SPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_LSP", DbType="Int NOT NULL")]
		public int Ma_LSP
		{
			get
			{
				return this._Ma_LSP;
			}
			set
			{
				if ((this._Ma_LSP != value))
				{
					if (this._LoaiSanPham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_LSPChanging(value);
					this.SendPropertyChanging();
					this._Ma_LSP = value;
					this.SendPropertyChanged("Ma_LSP");
					this.OnMa_LSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_SP", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Ten_SP
		{
			get
			{
				return this._Ten_SP;
			}
			set
			{
				if ((this._Ten_SP != value))
				{
					this.OnTen_SPChanging(value);
					this.SendPropertyChanging();
					this._Ten_SP = value;
					this.SendPropertyChanged("Ten_SP");
					this.OnTen_SPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Giaban", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Giaban
		{
			get
			{
				return this._Giaban;
			}
			set
			{
				if ((this._Giaban != value))
				{
					this.OnGiabanChanging(value);
					this.SendPropertyChanging();
					this._Giaban = value;
					this.SendPropertyChanged("Giaban");
					this.OnGiabanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Khuyenmai", DbType="Int")]
		public System.Nullable<int> Khuyenmai
		{
			get
			{
				return this._Khuyenmai;
			}
			set
			{
				if ((this._Khuyenmai != value))
				{
					this.OnKhuyenmaiChanging(value);
					this.SendPropertyChanging();
					this._Khuyenmai = value;
					this.SendPropertyChanged("Khuyenmai");
					this.OnKhuyenmaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Giakhuyenmai", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> Giakhuyenmai
		{
			get
			{
				return this._Giakhuyenmai;
			}
			set
			{
				if ((this._Giakhuyenmai != value))
				{
					this.OnGiakhuyenmaiChanging(value);
					this.SendPropertyChanging();
					this._Giakhuyenmai = value;
					this.SendPropertyChanged("Giakhuyenmai");
					this.OnGiakhuyenmaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mota", DbType="NVarChar(MAX)")]
		public string Mota
		{
			get
			{
				return this._Mota;
			}
			set
			{
				if ((this._Mota != value))
				{
					this.OnMotaChanging(value);
					this.SendPropertyChanging();
					this._Mota = value;
					this.SendPropertyChanged("Mota");
					this.OnMotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hinhanh", DbType="NVarChar(MAX)")]
		public string Hinhanh
		{
			get
			{
				return this._Hinhanh;
			}
			set
			{
				if ((this._Hinhanh != value))
				{
					this.OnHinhanhChanging(value);
					this.SendPropertyChanging();
					this._Hinhanh = value;
					this.SendPropertyChanged("Hinhanh");
					this.OnHinhanhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaydangban", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngaydangban
		{
			get
			{
				return this._Ngaydangban;
			}
			set
			{
				if ((this._Ngaydangban != value))
				{
					this.OnNgaydangbanChanging(value);
					this.SendPropertyChanging();
					this._Ngaydangban = value;
					this.SendPropertyChanged("Ngaydangban");
					this.OnNgaydangbanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soluongton", DbType="Int")]
		public System.Nullable<int> Soluongton
		{
			get
			{
				return this._Soluongton;
			}
			set
			{
				if ((this._Soluongton != value))
				{
					this.OnSoluongtonChanging(value);
					this.SendPropertyChanging();
					this._Soluongton = value;
					this.SendPropertyChanged("Soluongton");
					this.OnSoluongtonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Donvitinh", DbType="NVarChar(20)")]
		public string Donvitinh
		{
			get
			{
				return this._Donvitinh;
			}
			set
			{
				if ((this._Donvitinh != value))
				{
					this.OnDonvitinhChanging(value);
					this.SendPropertyChanging();
					this._Donvitinh = value;
					this.SendPropertyChanged("Donvitinh");
					this.OnDonvitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiSanPham_SanPham", Storage="_LoaiSanPham", ThisKey="Ma_LSP", OtherKey="Ma_LSP", IsForeignKey=true)]
		public LoaiSanPham LoaiSanPham
		{
			get
			{
				return this._LoaiSanPham.Entity;
			}
			set
			{
				LoaiSanPham previousValue = this._LoaiSanPham.Entity;
				if (((previousValue != value) 
							|| (this._LoaiSanPham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiSanPham.Entity = null;
						previousValue.SanPhams.Remove(this);
					}
					this._LoaiSanPham.Entity = value;
					if ((value != null))
					{
						value.SanPhams.Add(this);
						this._Ma_LSP = value.Ma_LSP;
					}
					else
					{
						this._Ma_LSP = default(int);
					}
					this.SendPropertyChanged("LoaiSanPham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHang")]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Ma_KH;
		
		private string _Hoten_KH;
		
		private string _Taikhoan_KH;
		
		private string _Matkhau_KH;
		
		private string _Gmail_KH;
		
		private System.Nullable<bool> _Xacthucgmail;
		
		private string _Anhdaidien_KH;
		
		private string _Diachi_KH;
		
		private string _Dienthoai_KH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_KHChanging(int value);
    partial void OnMa_KHChanged();
    partial void OnHoten_KHChanging(string value);
    partial void OnHoten_KHChanged();
    partial void OnTaikhoan_KHChanging(string value);
    partial void OnTaikhoan_KHChanged();
    partial void OnMatkhau_KHChanging(string value);
    partial void OnMatkhau_KHChanged();
    partial void OnGmail_KHChanging(string value);
    partial void OnGmail_KHChanged();
    partial void OnXacthucgmailChanging(System.Nullable<bool> value);
    partial void OnXacthucgmailChanged();
    partial void OnAnhdaidien_KHChanging(string value);
    partial void OnAnhdaidien_KHChanged();
    partial void OnDiachi_KHChanging(string value);
    partial void OnDiachi_KHChanged();
    partial void OnDienthoai_KHChanging(string value);
    partial void OnDienthoai_KHChanged();
    #endregion
		
		public KhachHang()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_KH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Ma_KH
		{
			get
			{
				return this._Ma_KH;
			}
			set
			{
				if ((this._Ma_KH != value))
				{
					this.OnMa_KHChanging(value);
					this.SendPropertyChanging();
					this._Ma_KH = value;
					this.SendPropertyChanged("Ma_KH");
					this.OnMa_KHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hoten_KH", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Hoten_KH
		{
			get
			{
				return this._Hoten_KH;
			}
			set
			{
				if ((this._Hoten_KH != value))
				{
					this.OnHoten_KHChanging(value);
					this.SendPropertyChanging();
					this._Hoten_KH = value;
					this.SendPropertyChanged("Hoten_KH");
					this.OnHoten_KHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Taikhoan_KH", DbType="VarChar(50)")]
		public string Taikhoan_KH
		{
			get
			{
				return this._Taikhoan_KH;
			}
			set
			{
				if ((this._Taikhoan_KH != value))
				{
					this.OnTaikhoan_KHChanging(value);
					this.SendPropertyChanging();
					this._Taikhoan_KH = value;
					this.SendPropertyChanged("Taikhoan_KH");
					this.OnTaikhoan_KHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Matkhau_KH", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Matkhau_KH
		{
			get
			{
				return this._Matkhau_KH;
			}
			set
			{
				if ((this._Matkhau_KH != value))
				{
					this.OnMatkhau_KHChanging(value);
					this.SendPropertyChanging();
					this._Matkhau_KH = value;
					this.SendPropertyChanged("Matkhau_KH");
					this.OnMatkhau_KHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gmail_KH", DbType="VarChar(100)")]
		public string Gmail_KH
		{
			get
			{
				return this._Gmail_KH;
			}
			set
			{
				if ((this._Gmail_KH != value))
				{
					this.OnGmail_KHChanging(value);
					this.SendPropertyChanging();
					this._Gmail_KH = value;
					this.SendPropertyChanged("Gmail_KH");
					this.OnGmail_KHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Xacthucgmail", DbType="Bit")]
		public System.Nullable<bool> Xacthucgmail
		{
			get
			{
				return this._Xacthucgmail;
			}
			set
			{
				if ((this._Xacthucgmail != value))
				{
					this.OnXacthucgmailChanging(value);
					this.SendPropertyChanging();
					this._Xacthucgmail = value;
					this.SendPropertyChanged("Xacthucgmail");
					this.OnXacthucgmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anhdaidien_KH", DbType="NVarChar(MAX)")]
		public string Anhdaidien_KH
		{
			get
			{
				return this._Anhdaidien_KH;
			}
			set
			{
				if ((this._Anhdaidien_KH != value))
				{
					this.OnAnhdaidien_KHChanging(value);
					this.SendPropertyChanging();
					this._Anhdaidien_KH = value;
					this.SendPropertyChanged("Anhdaidien_KH");
					this.OnAnhdaidien_KHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diachi_KH", DbType="NVarChar(200)")]
		public string Diachi_KH
		{
			get
			{
				return this._Diachi_KH;
			}
			set
			{
				if ((this._Diachi_KH != value))
				{
					this.OnDiachi_KHChanging(value);
					this.SendPropertyChanging();
					this._Diachi_KH = value;
					this.SendPropertyChanged("Diachi_KH");
					this.OnDiachi_KHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dienthoai_KH", DbType="VarChar(15)")]
		public string Dienthoai_KH
		{
			get
			{
				return this._Dienthoai_KH;
			}
			set
			{
				if ((this._Dienthoai_KH != value))
				{
					this.OnDienthoai_KHChanging(value);
					this.SendPropertyChanging();
					this._Dienthoai_KH = value;
					this.SendPropertyChanged("Dienthoai_KH");
					this.OnDienthoai_KHChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
